version: '3.4'

networks:
  infra:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  minio:
    driver: ${VOLUMES_DRIVER}
  docker-in-docker:
    driver: ${VOLUMES_DRIVER}

services:
### Minio ################################################
    minio:
      restart: always
      build: ./minio
      volumes:
        - ${DATA_PATH_HOST}/minio/data:/export
        - ${DATA_PATH_HOST}/minio/config:/root/.minio
      environment:
        - MINIO_ACCESS_KEY=laradock
        - MINIO_SECRET_KEY=laradock
      network_mode: host

### MySQL ################################################
    mysql:
      restart: always
      build:
        context: ./mysql
      environment:
        - MYSQL_DATABASE=default
        - MYSQL_USER=local
        - MYSQL_PASSWORD=local
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql:delegated
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
        - ${APP_CODE_PATH_HOST}/dumps:/dumps
      network_mode: host
      expose:
        - 3306
      ulimits:
        nproc: 65535
        nofile:
          soft: 26677
          hard: 46677

### Redis ################################################
    redis:
      restart: always
      build: ./redis
      volumes:
        - ${DATA_PATH_HOST}/redis:/data
      network_mode: host

### Mailhog ################################################
    mailhog:
      restart: always
      build: ./mailhog
      network_mode: host

### Docker-in-Docker ################################################
    docker-in-docker:
      restart: always
      image: docker:19.03-dind
      environment:
        DOCKER_TLS_SAN: DNS:docker-in-docker      
      privileged: true
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - docker-in-docker:/certs/client
      expose:
        - 2375
      network_mode: host

### REDIS COMMANDER ################################################
    redis-commander:
      restart: always
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
        - REDIS_HOSTS=local:127.0.0.1:6379
      network_mode: host

### ELASTIC MQ ################################################
    elasticmq:
      restart: always
      image: softwaremill/elasticmq-native:latest
      restart: always
      network_mode: host
      volumes:
        - ./elasticmq/custom.conf:/opt/elasticmq.conf

### DYNAMODB ################################################
    dynamodb:
      restart: always
      image: amazon/dynamodb-local:latest
      command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
      restart: always
      network_mode: host
      volumes:
        - "./.data/dynamodb:/home/dynamodblocal/data"
      working_dir: /home/dynamodblocal

### DYNAMODB ADMIN ################################################
    dynamodb-admin:
      restart: always
      build: ./dynamodb-admin
      environment:
        DYNAMO_ENDPOINT: "http://localhost:8000"
      restart: always
      network_mode: host